### ISSUE TITLE
PDK output scrollback in VS Code is extremely limited

### ISSUE THREAD

**Issue by rnelson0** [puppetlabs/pdk#829] opened 2020-01-16 20:17 UTC
**Describe the bug**
When running `pdk test unit` in a VS Code terminal, I expect to be able to scrollback through the output. (This is difficult to describe, hit me up on the community slack if you'd like to see it, but here goes) The test output only fills the terminal screen, whatever the height currently is. If you scroll back, you see things PRIOR to when you ran the PDK, but you do not see any PDK output.

If you run `pdk test unit | more`, you can pause the output and review it; same if you output to a file.

If this is unclear, follow the reproduction steps, then run the last command in a regular powershell window and compare the scrollback. It works fine in a regular powershell window.

**To Reproduce**
`pdk class new test`
Modify `spec\class\test_spec.rb` and add a dozen lines of `it { is_expected.to contain_package('foo') }` after the existing tests, save the file
Adjust your terminal height to ~20 lines
`pdk test unit --tests .\\spec\\class\\test_spec.rb`
The simplest sequence of steps you have discovered which triggers the bug.

**Expected behavior**
I expect the scrollback buffer in the terminal to be filled, and to be able to scroll back in the buffer and see output.

**Additional context**
- Your PDK installation method (native packages or via Rubygems) *chocolatey*
- Your PDK version (`pdk --version`) *1.15.0*
- Your operating system / platform *Windows 10 and VS Code with Puppet extension v0.22.0*

**Comment by rnelson0** [comment] 2020-01-16 20:54
Note: this happens with both the `Puppet PDK` terminal, from the Puppet extension, and my Integrated Terminal which uses `"terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",`

**Comment by jpogran** [comment] 2020-01-16 21:50
Output is truncated because of a setting in VSCode called `"terminal.integrated.scrollback"`, and it controls how many lines are kept, and it's default value is 1000. If you set it to anything larger, you get the full amount of output. You likely haven't see this in `powershell.exe`, `cmd.exe`, or the new Windows Terminal because those have larger scrollbacks by default.

**Comment by rnelson0** [comment] 2020-01-17 15:23
I uploaded a video at https://www.youtube.com/watch?v=5JFplRkRQa8 to better describe it.

**Comment by rnelson0** [comment] 2020-01-17 16:39
FWIW James and I spent quite a bit trying to reproduce this. James cannot reproduce it in any way, shape or form. I encounter it with disabled extensions, with a fresh VS code install, with various [terminal renderers](https://code.visualstudio.com/docs/editor/integrated-terminal#_changing-how-the-terminal-is-rendered) - no matter what I do, I ALWAYS see this in VSCode, but James can never see it. Hopefully some other parties can repro it.

**Comment by scotje** [comment] 2020-01-28 01:41
Only thing we noticed initially is that we should be able to skip using the `ansicon` wrapper for VS Code's embedded terminal. Perhaps that is messing with the buffer?

We've tagged this to investigate more for the February release, but if anyone else is able to reproduce this issue in their environment, please let us know.

**Comment by scotje** [comment] 2020-04-08 00:22
Going to close this for now until we can get some additional reproduction cases.

**Comment by edergillian** [comment] 2020-06-03 14:50
I have the exact same problem in my environment, although I'm running a very outdated PDK version (1.14.1). Everything else is up-to-date (VS Code 1.45.1, Puppet Extension 0.26.1).
I've been experiencing this problem for quite some time; I can't remember exactly when this started to happen, but it was somewhere around mid 2019. At the time, I thought it was related to a Puppet VSCode Extension update back then (it was still the James Pogran version, not the official Puppet one), but I rolled back to the previous one and still had the same issue.
Then I thought it was related to VSCode itself, but couldn't find any reference in their github issues. So I figured it must have been something related to my own computer and gave up trying to fix it. Whenever I need to analyse the pdk test output, I'd just open a separate powershell window and run the test there.

**Comment by jcitarello** [comment] 2021-02-26 18:12
I have this exact same problem and have been unable to identity the issue.

**Comment by jcitarello** [comment] 2021-02-26 20:15
Updated to pdk 2.0.0. Same issue.  Ran pdk validate twice here and this is the only terminal output I can see. Scroll bar was not present until I pulled up on the terminal screen.

![settings json](https://user-images.githubusercontent.com/6476294/109350306-e62cd200-783c-11eb-99d7-e77c7698e1b8.jpg)

**Comment by jcitarello** [comment] 2021-03-03 20:49
Discovered that this is issue is widespread across my department and none of us are able to use pdk with vscode any longer. Attempted to configure it on the wsl side, but the certificate configurations there is nothing short of a nightmare so my entire team is basically dead in the water now.

As a further desription of what is happening, pdk appears to be overrriding and/or wiping out the terminal buffer. To test:

Open terminal and type ctrl-c 50 times.

Run any pdk command (pdk validate, pdk test unit) and you'll see that it the output from the pdk command wipes out as much of the previous buffer as is produced. If I have 25 lines of pdk output, I can see 25 lines of the ctrl-c output wiped out.

This was originally 50 lines of crtl-c. You can see that much if it is now gone. Even some of the pdk output was wiped from the terminal buffer. This all seem to have started after they updated our workstations to Windows 10 - 1909. Pdk version does not seem to make a difference and have tested against 1.18.1 and the latest 2.0.0.

![pdk_capture](https://user-images.githubusercontent.com/6476294/109870085-4a7dd600-7c2f-11eb-83bf-c98e109e4b2b.JPG)

**Comment by rnelson0** [comment] 2021-03-04 01:49
FWIW I can pipe my command to more, it does limit how much I can see at a
time but does allow me to see the output of PDK. Sounds like that might be
of assistance if your whole team is blocked on this currently.
-- 
Rob Nelson

**Comment by jpogran** [comment] 2021-03-04 14:19
@jcitarello @edergillian @rnelson0 :

Can you try setting an environment variable before running a PDK command? I have a hypothesis that ansicon is interacting strangely with the VS Code hosted terminal. 

I'm suggesting using an existing environment variable from Windows Terminal or ConEMU, but it's just to trigger a different code path in the PDK init part.

Using the Windows Terminal env variable:

```
> $env:WT_SESSION = (New-Guid).Guid
> pdk <insert command>
```

Or using the ConEMU env variable::

```
> $env:ConEmuANSI = 'ON'
> pdk <insert command>
```

If that works, then I'll add a detection for the VS Code host and disable ansicon for that.

**Comment by jcitarello** [comment] 2021-03-04 14:46
@jpogran @edergillian @rnelson0 

Tested and everything seems to work alright with the WT_SESSION variable set. The one change I noticed is that instead of using the ansicon wrapper, the it's running a Ruby terminal while processing the pdk output. Goes back to "git" when finished. 

![ruby](https://user-images.githubusercontent.com/6476294/109980897-02f65900-7cc6-11eb-977c-976f01be6f88.JPG)


![session](https://user-images.githubusercontent.com/6476294/109980907-0558b300-7cc6-11eb-82b9-34c71d2b8473.JPG)

**Comment by jpogran** [comment] 2021-03-04 15:49
The 'ruby process, git process, ruby process' in the status is the 'normal' operation for things. The ansicon wrapper acts as a parent and 'hides' this to the external shell, so that experience makes sense.

Glad to hear its working so far for you. I'll wait for confirmation from the others for a bit before making a PR

**Comment by jcitarello** [comment] 2021-03-04 15:55
@jogran Thanks for the info. Is this actually a defect then? So curious to know what brought to light. Does it have something to do with the Windows 1909 build as I suspect, or something else?

**Comment by edergillian** [comment] 2021-03-04 17:58
@jpogran Thanks for the suggestion, it worked like a charm!

Waiting for the fix on the module, but I'll be using this workaround to get the job done.

**Comment by jpogran** [comment] 2021-03-04 21:04
@jcitarello It's not a defect per se, but instead an artifact of what ansicon is supposed to do. ansicon is supposed to backfill some ANSI escape sequence handling for the older conhost.exe. PDK uses it to have the color and spinner sequences look the same on older Windows as it does on macOS and on Linux. Since it's entire job is to change what is viewed on the terminal, it makes sense that its messing up terminals that can actually handle it.

It only occurred to me because you mentioned windows 10 1909 and it made me remember all the conhost.exe, conpty, and Windows Terminal ANSI and VT stuff they have been changing over the course of the 18XX to 1909 to 20H2 timeline. It occured to me that it was possible you were on a version that needed ansicon before, but now does not.

**Comment by scotje** [comment] 2021-03-04 21:36
@jpogran It may be worth considering inverting the logic of the ansicon wrapper at this point, so that instead of opting-out under known-good terminal emulators, we only opt-in to using ansicon under the old console? Not sure if there is a reliable way to detect the old console environment though.

**Comment by jpogran** [comment] 2021-03-04 22:16
At the moment, $env:TERM_PROGRAM is easier to detect than trying to figure out which version of Windows 10 added the support for ANSI escape sequences and properly detect that in a fast enough way to be executed every command.

I'll create an issue for long term using the version switcher instead, or evaluate even still using ansicon.

**Comment by jcitarello** [comment] 2021-03-05 14:27
@jpogran Thanks for helping to get this sorted out. I have been beating my head on my desk for a three weeks now trying to nail down what this issue actually was. It wasn't the easiest thing to try and duplicate on a consistent fashion.

**Comment by rnelson0** [comment] 2021-03-05 22:35
$env:WT_SESSION = (New-Guid).GuidThat works for me! Wow, this has been haunting me for like half a year now, and suddenly it works as expected and if I leave off `|more` I don't have to start over. Thanks so much @jpogran, I added that to my $profile and everything's looking a lot better.

You really have no idea how much this improves things for me!

**Comment by jpogran** [comment] 2021-03-08 01:12
Apologies for taking this long to figure it out. I have a PR up to fix things in the PDK, until a new release please continue to use the workaround.

**Comment by rnelson0** [comment] 2021-03-09 01:56
Oh please do not worry about the time it took. I'd have been waiting for the heat death of the universe to find that setting on my own, so I'm extremely tickled about this!

**Closed** 2021-03-09 16:50 UTC
Labels: bug, external
