### ISSUE TITLE
The regex style demanded by pdk validate should allow the (?x) option to be better leveraged

### ISSUE THREAD

**Issue by jcbollinger** [puppetlabs/pdk#469] opened 2018-04-05 16:22 UTC
Ruby regular expression syntax, as supported by Puppet in conjunction with the `Pattern` data type and elsewhere, affords an `x` option that can be specified inline.  This option makes whitespace and Ruby-style comments insignificant in patterns, which is a great mechanism for making regular expressions more readable and comprehensible.  Surely readable, comprehensible regular expressions are better style than unreadable ones?

But the style rules enforced by default by `pdk validate` seem not to allow the `x` option to be fully leveraged.  The option itself may appear, but validation fails if (insignificant) line breaks appear.  Inasmuch as embedded line breaks are a prerequisite for embedded comments, it therefore also fails to validate regular expressions with embedded comments.  This is counter-productive.

Here's a real-world example.  Which of these should be the preferred style?

**Style 1: without any insignificant whitespace in the pattern**
```
#
# A data type describing an IPv6-wrapped IPv4 address
#
type Sb::Ipv6_ipv4address = Pattern[
  /(?i)\A(?:[:](?:[:]0{1,4}){0,4}[:]|(?!(?:0[:].*){5})(?:0{1,4}[:]){1,4}(?:[:]0{1,4}){0,3}[:]|(?:0{1,4}[:]){5})ffff[:](?:(?!25[6-9]|[3-9]\d{2})\d{1,3}[.]){3}(?:(?!25[6-9]|[3-9]\d{2})\d{1,3})\z/
]
```

**Style 2: without comments or line breaks in the pattern**
```
#
# A data type describing an IPv6-wrapped IPv4 address
#
type Sb::Ipv6_ipv4address = Pattern[
  /(?ix)\A (?: [:] (?: [:]0{1,4} ){0,4} [:] | (?! (?: 0[:].* ){5} ) (?: 0{1,4}[:] ){1,4} (?: [:]0{1,4} ){0,3} [:] | (?: 0{1,4}[:] ){5}) ffff[:] (?: (?! 25[6-9]|[3-9]\d{2} ) \d{1,3}[.] ){3} (?: (?! 25[6-9]|[3-9]\d{2} ) \d{1,3} ) \z/
]
```

**Style 3: with comments and line breaks clarifying and documenting pattern structure**
```
#
# A data type describing an IPv6-wrapped IPv4 address
#
type Sb::Ipv6_ipv4address = Pattern[
  /(?ix)\A
    # IPv6 prefix
    (?:
      # leading or bare ::
      [:] (?: [:]0{1,4} ){0,4} [:]

      # middle or trailing ::
      | (?! (?: 0[:].* ){5} )
        (?: 0{1,4}[:] ){1,4}
        (?: [:]0{1,4} ){0,3}
        [:]

      # no ::
      | (?: 0{1,4}[:] ){5}
    )
    ffff[:]

    # IPv4 piece
    (?: (?! 25[6-9]|[3-9]\d{2} ) \d{1,3}[.] ){3}
    (?: (?! 25[6-9]|[3-9]\d{2} ) \d{1,3} )
  \z/
]
```

I submit that the last is far preferable to the other two, but it fails validation.

Amusingly, although the former two styles pass validation, they elicit a warning about the very long line. PDK's got me both coming and going.

**Comment by rodjek** [comment] 2019-03-20 01:42
This is also being tracked in https://tickets.puppetlabs.com/browse/PDK-1178

**Comment by sanfrancrisko** [comment] 2021-04-09 10:47
I'm closing this issue @jcbollinger as it appears as though the issue is resolved. I tested a few multi line regex patterns using PDK 2.1 (w/ `puppet-line 2.4.1`) along with the 3rd style example you gave above.

Feel free to comment on the ticket if you're still having issues though.

**Closed by sanfrancrisko** 2021-04-09 10:47 UTC
Labels: JIRA, pdk-validate
