### ISSUE TITLE
`pdk new module foo` fails with wrong number of arguments (given 2, expected 1)

### ISSUE THREAD

**Issue by klemensn** [puppetlabs/pdk#1254] opened 2023-06-05 15:58 UTC
**Describe the bug**
https://www.puppet.com/docs/pdk/2.x/pdk_creating_modules.html, `dpk32 new module --help` and `dpk32 new module foo` have three different opinions about synopsis and number of arguments.

1. https://www.puppet.com/docs/pdk/2.x/pdk_creating_modules.html#create-a-module says `pdk new module <MODULE_NAME>` or `pdk new module <MODULE_NAME> --skip-interview`
2. `dpk32 new module --help` says
```
...
USAGE
    pdk new module [options] [module_name]
    [target_dir]
...
```

Usage in 1. (option after module name) does not match synopsis in 2. (options after module name).

Regardless of options and/or optional target directory, creating a new module always fails:
```
$ pdk32 new module foo
/home/kn/.local/share/gem/ruby/3.2/gems/pdk-2.7.1/lib/pdk/analytics/client/noop.rb:13:in `screen_view': wrong number of arguments (given 2, expected 1) (ArgumentError)
        from /home/kn/.local/share/gem/ruby/3.2/gems/pdk-2.7.1/lib/pdk/cli/util.rb:299:in `analytics_screen_view'
        from /home/kn/.local/share/gem/ruby/3.2/gems/pdk-2.7.1/lib/pdk/cli/new/module.rb:24:in `block (2 levels) in <module:CLI>'
        from /home/kn/.local/share/gem/ruby/3.2/gems/cri-2.15.11/lib/cri/command.rb:362:in `run_this'
        from /home/kn/.local/share/gem/ruby/3.2/gems/cri-2.15.11/lib/cri/command.rb:298:in `run'
        from /home/kn/.local/share/gem/ruby/3.2/gems/cri-2.15.11/lib/cri/command.rb:316:in `run'
        from /home/kn/.local/share/gem/ruby/3.2/gems/cri-2.15.11/lib/cri/command.rb:316:in `run'
        from /home/kn/.local/share/gem/ruby/3.2/gems/pdk-2.7.1/lib/pdk/cli.rb:55:in `run'
        from /home/kn/.local/share/gem/ruby/3.2/gems/pdk-2.7.1/exe/pdk:6:in `<top (required)>'
        from /home/kn/.local/share/gem/ruby/3.2/bin/pdk32:25:in `load'
        from /home/kn/.local/share/gem/ruby/3.2/bin/pdk32:25:in `<main>'
```
```
$ pdk32 new module foo bar
/home/kn/.local/share/gem/ruby/3.2/gems/pdk-2.7.1/lib/pdk/analytics/client/noop.rb:13:in `screen_view': wrong number of arguments (given 2, expected 1) (ArgumentError)
	from /home/kn/.local/share/gem/ruby/3.2/gems/pdk-2.7.1/lib/pdk/cli/util.rb:299:in `analytics_screen_view'
	from /home/kn/.local/share/gem/ruby/3.2/gems/pdk-2.7.1/lib/pdk/cli/new/module.rb:24:in `block (2 levels) in <module:CLI>'
	from /home/kn/.local/share/gem/ruby/3.2/gems/cri-2.15.11/lib/cri/command.rb:362:in `run_this'
	from /home/kn/.local/share/gem/ruby/3.2/gems/cri-2.15.11/lib/cri/command.rb:298:in `run'
	from /home/kn/.local/share/gem/ruby/3.2/gems/cri-2.15.11/lib/cri/command.rb:316:in `run'
	from /home/kn/.local/share/gem/ruby/3.2/gems/cri-2.15.11/lib/cri/command.rb:316:in `run'
	from /home/kn/.local/share/gem/ruby/3.2/gems/pdk-2.7.1/lib/pdk/cli.rb:55:in `run'
	from /home/kn/.local/share/gem/ruby/3.2/gems/pdk-2.7.1/exe/pdk:6:in `<top (required)>'
	from /home/kn/.local/share/gem/ruby/3.2/bin/pdk32:25:in `load'
	from /home/kn/.local/share/gem/ruby/3.2/bin/pdk32:25:in `<main>'
```
(Same backtrace if I pass `--skip-interview` before or after `foo`.)

**To Reproduce**
Install PDK from Rubygems on OpenBSD/amd64 7.3-current with `gem32 install --user-install pdk`.

**Expected behavior**
A new module should be created.

**Additional context**
```
$ ruby32 --version
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-openbsd]
```
```
$ gem32 --version
3.4.10
```
```
$ export PATH=$PATH:$HOME/.local/share/gem/ruby/3.2/bin
$ pdk32 --version
2.7.1
```
```
$ uname -m -r -s -v
OpenBSD 7.3 GENERIC.MP#1215 amd64
```

**Comment by binford2k** [comment] 2023-06-06 20:14
Duplicate of #1171

**Closed by binford2k** 2023-06-06 20:14 UTC
Labels: bug, needs-triage, community
