### ISSUE TITLE
Installing PDK from .deb causes unmet dependencies on Ubuntu 17.10 Artful

### ISSUE THREAD

**Issue by bittner** [puppetlabs/pdk#370] opened 2017-12-04 16:22 UTC
We're setting up developer desktop machines based on Ubuntu 17.10 Artful using The Foreman and Puppet, and it looks like installing PDK from the official .deb is causing unmet dependencies in the machine setup: (excerpt from the Puppet logs in our Foreman instance)

```bash
The following packages have unmet dependencies:
pdk : Depends: libreadline6 but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```

This is failing the entire build, the error returns repeatedly for all dpkg/apt install attempts.

We're installing the PDK from a simple Puppet class as follows, which works fine on a machine that is already set up with Ubuntu:

```puppet
class profile::development {
  # ... (other stuff) ...

  package { 'pdk':
    ensure   => present,
    source   => '/tmp/pdk.deb',
    require  => Archive['/tmp/pdk.deb'],
    provider => dpkg,
  }

  archive { '/tmp/pdk.deb':
    source  => 'https://pm.puppetlabs.com/cgi-bin/pdk_download.cgi?dist=ubuntu&rel=16.04&arch=amd64&ver=latest',
    extract => false,
    cleanup => false,
  }
}
```

I would guess that PDK requires `libreadline6` and this can not be installed by dpkg, is this correct? I will now try installing `libreadline6` using Puppet and a `require => Package['libreadline6']` option.

In the long run, though, I would prefer to be able to install the PDK via a Debian repo, by simply running `apt-get install pdk`. Is this already on the roadmap?

**Comment by scotje** [comment] 2017-12-04 17:32
I suspect the issue is because the Ubuntu packages are built for `14.04` and `16.04`, building a new package specifically for `17.10` would hopefully resolve the dependency issue.

As far as installing from a repo, yes it is definitely on our near-term roadmap already. The PDK project ticket to track that is https://tickets.puppetlabs.com/browse/PDK-586 although there is some tooling work that is currently holding that up.

In the short term we can evaluate adding the latest Ubuntu to the list of platforms we package for.

**Comment by scotje** [comment] 2017-12-15 14:14
@bittner When 18.04 is released in April of next year do you think your developers will be adopting that fairly quickly? We will definitely be releasing packages for 18.04 but are trying to evaluate the need for a 17.10 release before then.

**Comment by bittner** [comment] 2017-12-15 23:03
@scotje Yes, I believe we will. The reason is simple: We use Puppet (and The Foreman) for setting up our office infrastructure (including workstations) in a fully automatic fashion, so we can experiment easily and move quickly!  :smile: 

We've managed to get the installation working as described above. So, this issue is really about:

1. .deb's for all Ubuntu releases, and
1. PDK easily installable from an official Debian repository or PPA

It would be good if https://tickets.puppetlabs.com/browse/PDK-586 could be implemented. This issue would be resolved this way.

Thank!

**Comment by scotje** [comment] 2017-12-15 23:42
Sounds good, I agree on both fronts. We've discovered some extra infrastructure work we'll need to explore for item 1, but there should be good news about PDK-586 shortly. 😉

**Comment by scotje** [comment] 2018-03-21 23:51
PDK is now included in the official Puppet platform package repositories!

After further evaluation we probably won't be building packages specifically for Ubuntu 17.10 but we will have packages for 18.04 shortly after that releases next month.

**Closed by scotje** 2018-03-21 23:51 UTC
