### ISSUE TITLE
PDK 3.2.0 missing from Puppet 7 EL 7 and 8 repodata 

### ISSUE THREAD

**Issue by nabertrand** [puppetlabs/pdk#1361] opened 2024-05-28 17:01 UTC
**Describe the bug**
Even though PDK 3.2.0 RPMs appear in both repos, e.g. https://yum.puppet.com/puppet7/el/7/x86_64/pdk-3.2.0.1-1.el7.x86_64.rpm and https://yum.puppet.com/puppet7/el/8/x86_64/pdk-3.2.0.1-1.el8.x86_64.rpm, the repodata for the repos seems to only include RPMs up to PDK 3.0.1.

**To Reproduce**
Install the Puppet 7 EL 7 or EL 8 repos and attempt to install the PDK package. The latest available package is 3.0.1.3:
```
# yum install pdk
...
Resolving Dependencies
--> Running transaction check
---> Package pdk.x86_64 0:3.0.1.3-1.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

====================================================================================================
 Package            Arch                  Version                      Repository              Size
====================================================================================================
Installing:
 pdk                x86_64                3.0.1.3-1.el7                pc_repo                103 M
```

**Expected behavior**
PDK 3.2.0.1 is installed

**Additional context**
- Your PDK installation method (native packages or via Rubygems): Native packages
- Your PDK version (`pdk --version`): 3.0.1
- Your operating system / platform: CentOS 7 x86_64 and Rocky 8 x86_64

**Comment by nabertrand** [comment] 2024-05-28 17:04
FYI I also received three `[puppetlabs/pdk] Run failed: Labeller - main` emails when I created this issue. It looks like labels were added, so I'm not sure what the issue was.

**Comment by LukasAud** [comment] 2024-05-30 15:27
We tried to replicate this issue on a docker container following our official documentation: https://www.puppet.com/docs/pdk/3.x/pdk_install.html#install-on-rhel-sles-or-fedora

We were not able to reproduce the problem. According to our documentation, the recommended yum link would be:
https://yum.puppet.com/puppet-tools-release-el-7.noarch.rpm

Could you try reproducing with the above instructions? We are going to close the issue for now. If the problem persists, please feel free to reopen.

**Closed by LukasAud** 2024-05-30 15:27 UTC
Labels: bug, needs-triage

**Comment by nabertrand** [comment] 2024-05-31 04:51
Thanks for looking into this @LukasAud. I am able to install PDK 3.2.0 by adding the puppet-tools repo as you described, but I guess I'm confused why the PDK RPMs are added to the Puppet 7 platform repos as well but not updated in the repo metadata. Is the version in the Puppet 7 platform repos intentionally held to 3.0.1 even though the 3.2.0 RPMs exist in the repos? It seems like perhaps the repo metadata in the Puppet 7 platform repos just needs to be rebuilt to include the latest PDK RPMs. Here's what I see adding just the Puppet 7 platform repo as described in the [installation docs](https://www.puppet.com/docs/puppet/7/install_puppet#enable_the_puppet_platform_repository)
```
# yum install https://yum.puppet.com/puppet7-release-el-8.noarch.rpm
# dnf install pdk
Last metadata expiration check: 0:03:03 ago on Thu 30 May 2024 11:44:07 PM CDT.
Dependencies resolved.
==============================================================================================
 Package          Architecture        Version                      Repository            Size
==============================================================================================
Installing:
 pdk              x86_64              3.0.1.3-1.el8                puppet7              103 M

Transaction Summary
==============================================================================================
Install  1 Package
```
