### ISSUE TITLE
'pdk validate --parallel' produces garbled output

### ISSUE THREAD

**Issue by natemccurdy** [puppetlabs/pdk#795] opened 2019-10-31 18:14 UTC
**Describe the bug**
When running `pdk validate --parallel`, the output is garbled. Lines get squashed together, indentation is all over the place and characters/words are missing.

Here's an example:
![pdk validate parallel](https://user-images.githubusercontent.com/10200384/67974119-0445dc00-fbcf-11e9-96ae-ff9c10bcfdd4.gif)

**To Reproduce**
```
~/pdk_module/ $ pdk validate --parallel
```

**Expected behavior**
Each line of validation text should be clearly legible, consistently indented, and not squashed into other lines.

**Additional context**
- PDK 1.13.0 installed from the official DMG
- MacOS 10.14.6
- iTerm 3.3.20191004-nightly
- ZSH 5.7.1
- Front - ASCII: Menlo
- Front - Non-ASCII: Iconsolata Awesome

**Comment by scotje** [comment] 2019-10-31 18:23
This is also tracked in https://tickets.puppetlabs.com/browse/PDK-1032

There is some underlying issues with the parallel threading code that this is a symptom of.

**Comment by sanfrancrisko** [comment] 2021-04-12 15:00
Ran this again on version `2.1` of the PDK - seems like things are not quite as bad, although there is still some weirdness in the output of the spinners when running with `--parallel`. 

Given [PDK-1215](https://tickets.puppetlabs.com/browse/PDK-1215) was marked a dupe of [PDK-1032](https://tickets.puppetlabs.com/browse/PDK-1032), neither seemed to be worked upon and this ticket got removed from it's original Milestone but no new one added, it's probably worth some investigation in to what's happening in the code.

@natemccurdy please excuse the amount of time that's passed since we looked at this - we're trying to jump start development on the PDK again and are going through a number of issues, triaging them. If you have any more comments, with a later version of PDK, please feel free to drop them here.

**Comment by natemccurdy** [comment] 2021-04-12 21:23
@sanfrancrisko Tried again with PDK 2.1.0, but am still seeing the problem.

Here's a new gif:
![pdk 2 1 0 validate parallel](https://user-images.githubusercontent.com/10200384/114464473-a9256080-9b9a-11eb-9c9c-107fbc3324d5.gif)

**Comment by sanfrancrisko** [comment] 2021-04-14 15:22
Thanks for providing the GIF @natemccurdy 

I do see weirdness in the bog standard macOS terminal too. My env is:

- PDK 2.1.0
- macOS 10.15.7
- Terminal (native OS version) 2.10 (433)
- zsh 5.7.1

![validate_parallel](https://user-images.githubusercontent.com/55992494/114735880-83848c80-9d3d-11eb-83f7-b0f2fd71133c.gif)

**Comment by sanfrancrisko** [comment] 2021-09-20 10:44
This ticket will not be addressed in it's current form, but the issue will be considered in the future roadmap of the new PDK: https://puppet.com/blog/the-future-of-the-puppet-developer-kit-pdk/

**Closed by sanfrancrisko** 2021-09-20 10:44 UTC
Labels: bug, pdk-validate
