### ISSUE TITLE
PDK v2.7.0 and PDK 2.7.1 crash trying to run unit tests

### ISSUE THREAD

**Issue by jcbollinger** [puppetlabs/pdk#1256] opened 2023-06-14 19:28 UTC
**Describe the bug**
In PDK 2.7.0 and 2.7.1, the command `pdk test unit` crashes with a `rake` error:
```
[jbolling@svlpsbpuppet01 pdk271_test]$ pdk test unit
pdk (INFO): Using Ruby 2.7.7
pdk (INFO): Using Puppet 7.23.0
[✖] Preparing to run the unit tests.
[✖] Cleaning up after running unit tests.
pdk (ERROR): The spec_clean rake task failed with the following error(s):

rake aborted!
LoadError: cannot load such file -- puppet_blacksmith/rake_tasks
/home/whitegrp/jbolling/puppet-clone/code/environments/production/modules/pdk271_test/Rakefile:7:in `require'
/home/whitegrp/jbolling/puppet-clone/code/environments/production/modules/pdk271_test/Rakefile:7:in `<top (required)>'
/opt/puppetlabs/pdk/share/cache/ruby/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)

pdk (FATAL): Failed to clean up after running unit tests
```
I encountered this issue in conjunction with an existing module, after upgrading from PDK 2.6.1 to PDK 2.7.0, but I find that I can reproduce it even with a brand new skeleton module.

**To Reproduce**
 1. Install PDK 2.7.1.
 2. Create a new module with `pdk new module`
 3. In the new module, run `pdk test unit`

**Expected behavior**
The test suite should run successfully.

**Additional context**
- Installed from native packages via `yum`, from the repository at http://yum.puppetlabs.com/puppet7/el/7/x86_64
- PDK version 2.7.1
- RHEL 7.9

**Comment by nabertrand** [comment] 2023-06-14 21:03
I've run into this myself with the `github_changelog_generator` gem. The issue is that if you use the PDK with a module that includes one of the optional gems searched for in the Rakefile, the Rakefile from your module finds the cached gem and expects it to be included in the bundle. Here's a snippet from the pdk-template Rakefile:
```ruby
require 'puppet_litmus/rake_tasks' if Bundler.rubygems.find_name('puppet_litmus').any?
require 'github_changelog_generator/task' if Bundler.rubygems.find_name('github_changelog_generator').any?
require 'puppet-strings/tasks' if Bundler.rubygems.find_name('puppet-strings').any?
```
If any of those gems exist in the cache but are not included in your module Gemfile, the Rakefile fails to load as you saw. I worked around this by manually purging the problem gem from the PDK cache:
```bash
$ pdk bundle exec rake -T
pdk (INFO): Using Ruby 2.7.7
pdk (INFO): Using Puppet 7.24.0
rake aborted!
LoadError: cannot load such file -- github_changelog_generator/task
$ find ~/.pdk/cache/ -name 'github_changelog_generator*.gemspec' -delete
pdk bundle exec rake -T
pdk (INFO): Using Ruby 2.7.7
pdk (INFO): Using Puppet 7.24.0
rake build                               # Build puppet module package
...
```
Is there perhaps a bundle-specific version of `Bundler.rubygems.find_name` that only find gems included in the current bundle?

**Comment by nabertrand** [comment] 2023-06-14 21:22
Some quick searches suggest `Gem.loaded_specs.key?` might be a better check than `Bundler.rubygems.find_name`, e.g.
```ruby
require 'github_changelog_generator/task' if Gem.loaded_specs.key? 'github_changelog_generator'
```

**Comment by jcbollinger** [comment] 2023-06-14 22:51
> I've run into this myself with the `github_changelog_generator` gem. The issue is that if you use the PDK with a module that includes one of the optional gems searched for in the Rakefile, the Rakefile from your module finds the cached gem and expects it to be included in the bundle.

Interesting, @nabertrand .  None of my modules under test bundles any gems, but I nevertheless did find a couple of different copies of the `puppet_blacksmith` gem in my `~/.pdk/cache`.  Presumably they got there via some dependency of one or more of my modules.  Clearing them out resolved the test crashes, but they came back when I ran my omnibus test suite, *after* which, my tests started crashing again.

**Comment by jordanbreen28** [comment] 2023-08-03 07:35
Closing as this was resolved in pdk-templates/

**Closed by jordanbreen28** 2023-08-03 07:35 UTC
Labels: bug, needs-triage, community
